name: MysticEnchantments
version: '1.15.1'
main: com.mdt168.mysticEnchantments.MysticEnchantments
api-version: '1.21.4'
authors: [ MDT168 ]
bootstrapper: com.mdt168.mysticEnchantments.MyPluginBootstrap
description: Adds loads of custom enchantments to the game with a new humane enchantments system.
